# Generated by Django 3.2 on 2021-04-28 08:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Owners',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=45)),
                ('email', models.EmailField(max_length=300)),
                ('age', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Owners',
            },
        ),
        migrations.CreateModel(
            name='Dog',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=45)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('owners', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='owners.owners', verbose_name='owners')),
            ],
            options={
                'db_table': 'Dog',
            },
        ),
    ]
