# Generated by Django 3.2 on 2021-04-28 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('owners', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Dog',
            new_name='Dogs',
        ),
    ]
