# Generated by Django 3.2 on 2021-04-29 02:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actors',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=45)),
                ('last_name', models.CharField(max_length=45)),
                ('date_of_birth', models.DateField()),
            ],
            options={
                'db_table': 'actors',
            },
        ),
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=45)),
                ('release_date', models.DateField()),
                ('runnig_time', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'moives',
            },
        ),
        migrations.CreateModel(
            name='Actors_Movies',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.actors', verbose_name='actors')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.movies', verbose_name='movies')),
            ],
            options={
                'db_table': 'actiors_movies',
            },
        ),
        migrations.AddField(
            model_name='actors',
            name='movies',
            field=models.ManyToManyField(through='movies.Actors_Movies', to='movies.Movies', verbose_name='movies'),
        ),
    ]
