# Generated by Django 3.2 on 2021-04-29 04:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='actors_movies',
            table='actors_movies',
        ),
        migrations.AlterModelTable(
            name='movies',
            table='movies',
        ),
    ]
