# Generated by Django 3.2 on 2021-04-29 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_alter_movies_release_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actors',
            name='movies',
            field=models.ManyToManyField(related_name='actors', through='movies.Actors_Movies', to='movies.Movies', verbose_name='movies'),
        ),
    ]
